spring:
  profiles:
    active: prod

---
spring:
  profiles: test
config:
  name: test
  environment: test-YAML
  servers:
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
  profiles: prod
config:
  name: prod
  environment: prod_YAML
  servers:
    - www.abc.com
    - www.xyz.com
